const quotes = [
      { text: "God will give you a testimony that will cancel years of mockery."},
      { text: "The presence of God is the cure for pressure."},
      { text: "When you are in the will of God, every storm works for your good."},
      { text: "Your worship is a weapon. It breaks chains you don't even see."},
      { text: "If you want to see God's hand, obey His voice."},
      { text: "you can't make a difference without a reason."},
      { text: "If you don't aim well you can't end well. Your aim determines your end."},
      { text: "Nothing purposed is nothing pursued and nothing pursued is nothing possessed."},
      { text: "Your possibilities in life are tied around your potentials."},
      { text: "Your endowment is linked to your uplifting. Your gift is key to your lift."},
      { text: "Not every business is your business. There is one that would make you known in the world-find it."},
      { text: "If God leads the way, a table is prepared."},
      { text: "Your place is where blessing that is in a hurry looks for you. Look for that place."},
      { text: "You cannot get anywhere living anyhow."},
      { text: "You cannot live carelessly and end gloriously."},
      { text: "You cannot out love God."},
      { text: "Once you have the desire and you don't have the discipline, all you have is a wish."},
      { text: "You cannot out worship God."},
      { text: "those who place themselves under commandments become commanders."},
      { text: "You cannot out give God, because He is the source of all blessings."},
      { text: "Until questions are asked, answers are not accessed."},
      { text: "The will of God will never take you where the grace of God will not protect you."},
      {text: "There is the voice in the verse, the spirit behind the letter."},
      { text: " Who can make a door against the way."},
      { text: "When you are in the will of God, you are in the place of peace, provision, protection, promotion, power and purpose."},
      { text: "When you are in the will of God, you are in the place of peace."},
      { text: "When you are in the will of God, you are in the place of provision."},
      { text: "When you are in the will of God, you are in the place of protection."},
      { text: "When you are in the will of God, you are in the place of promotion."},
      { text: "When you are in the will of God, you are in the place of power."},
      { text: "When you are in the will of God, you are in the place of purpose."},
      { text: "When you are in the will of God, you are in the place of peace, provision, protection, promotion, power and purpose."},
      { text: "Don't be in a hurry to show up otherwise you blow up."},
      { text: "People may mock your praise but God will bless you for your praise."},
      { text: "The way you start a thing is the way you finish it."},
      { text: "You cannot give what you do not have."},
      { text: "Your level of success is determined by your level of discipline and perseverance."},
      { text: "The only thing that can stop you from fulfilling your destiny is you."},
      { text: "You are not where you are by mistake, you are where you are by divine appointment."},
      { text: "The greatest enemy of progress is comfort."},
      { text: "If you want to fly, you have to give up the things that weigh you down."},
      { text: "Don't over celebrate principles, celebrate practices."},
      { text: "Knowledge is not power until it is applied."},
      { text: "The value of knowledge is not in knowing, but in doing."},
      { text: "Even though you live by faith, there are times where faith becomes foolishness."},
      { text: "When you lose the mentality of the Almighty, you decend into the calamity of stupidity."},
      { text: "What you know makes you intelligent but what you do with what you know makes you wise."},
      { text: "don't over celebrate what you know, celebrate what you are doing with what you know."},
      { text: "When you lose the mentality of a winner, you become a loser."},
      { text: "A wise man is a specialist of difficulties."},
      { text: "It is better to take a stand for good even if you have to stand alone."},
      { text: "You are not careful about your destiny until you are careful about your company."},
      { text: "There is a connection between reasoning and sinfulness."},
      { text: "Society's influence can affect character. It may be popular but not necessarily proper."},
      { text: "It is better for people to follow you in doing right than for you to follow them in doing wrong."},
      { text: "When you are far from the Word, you get lost in the world; but when you are close to the Word, you stay faraway from the world,"},
      { text: "Loveless hearts are behind sinful lives. The fear of God is the bedrock of godly character."},
      { text: "Nothing corrupts character like bad company."},
      { text: "Character can be corrected by good company and corrupted by bad compny."},
      { text: "Love will lead you to end your journey with God why hate will lead you to end your journey with the devil."},
      { text: "The bankruptcy of love is the bankruptcy of character"},
      { text: "In love, wether people are present or absent, their value remaiins the same in your eyes."},
      { text: "The absence of love is the presence of selfishness. Lovelessness is characterless."},
    ];